### ISSUE TITLE
Extract depth image from rosbag

### ISSUE THREAD

**Issue by yicheng6o6** [EPVelasco/pc2image#2]
Hi, Thank you for the great work:)

I run **rosbag record -O out /depth_image** command to record the **/depth_image** topic and I get a .bag file. But I don't know how to extract these depth images from .bag file. I want to collect these data to train a network for pose estimation.

I would be grateful if you could give me some suggestions to achieve it.

Best wishes,
Yicheng

**Comment by EPVelasco** [comment]
hi, you can check the ROS [image_view](http://wiki.ros.org/image_view) tutorial.

In a terminal type

```
mkdir folder_images
cd folder_images
rosrun image_view image_saver image:=/depth_image
```
In another terminal type
```
rosbag play "name_of_your_rosbag_file"
```
The generated files are the images in .jpg format of your rosbag file

Good luck, bye.

**Comment by yicheng6o6** [comment]
Thank you very much!
I will learn and do it :)
